@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTEzMzc2NDF9.xNLb79ZtGC57cyvNcTRG5GnNN3Oc3eL4lrEfgdAGLD0

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "amanda",
  "user_name": "useramanda",
  "email": "amanda@test.com",
  "password": "password",
  "password_confirmation": "password"
}
### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "amanda@test.com",
  "password": "password"
}
### Libraries index
GET http://localhost:3000/libraries
Authorization: Bearer {{jwt}}
### Libraries show
GET http://localhost:3000/libraries/8
Authorization: Bearer {{jwt}}

###Libraries create
POST http://localhost:3000/libraries
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "game_id": "4000",
  "rating": "4"
}
### Libraries update
PATCH http://localhost:3000/libraries/8
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
 "rating": "6"
}
### Libraries destroy
DELETE http://localhost:3000/libraries/11
Authorization: Bearer {{jwt}}
### Games index
GET http://localhost:3000/games
### Games show
GET http://localhost:3000/games/3498
### Games index tesing search
GET http://localhost:3000/games
Content-Type: application/json

{
  "search": "portal 2"
}